// <auto-generated />
namespace TrashPickup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingsoyoutracknumberofpickups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingsoyoutracknumberofpickups));
        
        string IMigrationMetadata.Id
        {
            get { return "201709111957587_adding so you track number of pickups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
