// <auto-generated />
namespace TrashPickup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedstringtointforstatesid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedstringtointforstatesid));
        
        string IMigrationMetadata.Id
        {
            get { return "201709071831333_changed string to int for states id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
